## This will be my "playground" notebook for the early part of the PyTorch class. I'll take notes and retype all of the examples from the intro section of the class. The idea is to develop some "muscle memory" as well as best practices for using PyTorch.

In PyTorch, matrices are referred to as tensors, where as in Numpy, they are referred to as ndarrays. 

### 1.1 Creating Matrices

In [1]:
import numpy as np

In [2]:
# creating an array with lists
arr = [[1,2],[3,4]]
print(arr)

[[1, 2], [3, 4]]


In [3]:
#Convert to Numpy ndarray
np.array(arr)

array([[1, 2],
       [3, 4]])

In [4]:
import torch

In [5]:
#Convert first array to a PyTorch tensor
torch.Tensor(arr)


 1  2
 3  4
[torch.FloatTensor of size 2x2]

### 1.2 Creating Matrices with Default Values

In [6]:
np.ones((2,2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [7]:
# same as...
torch.ones((2,2))


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [9]:
np.random.rand(2,2) #Numpy array of random numbers

array([[ 0.77030648,  0.49306204],
       [ 0.67015071,  0.78558532]])

In [10]:
torch.rand(2,2) # Easy as that in PyTorch


 0.3351  0.1051
 0.9270  0.5361
[torch.FloatTensor of size 2x2]

### 1.3 Seeds for reproducibility

In [14]:
#Seed
np.random.seed(0)
np.random.rand(2,2)

array([[ 0.5488135 ,  0.71518937],
       [ 0.60276338,  0.54488318]])

In [15]:
#Same Seed
np.random.seed(0)
np.random.rand(2,2)

array([[ 0.5488135 ,  0.71518937],
       [ 0.60276338,  0.54488318]])

In [12]:
#No Seed
np.random.rand(2,2)

array([[ 0.69772882,  0.2160895 ],
       [ 0.97627445,  0.00623026]])

In [13]:
#No Seed
np.random.rand(2,2)

array([[ 0.25298236,  0.43479153],
       [ 0.77938292,  0.19768507]])

In [16]:
#Seeds in Torch
torch.manual_seed(0)
torch.rand(2,2)


 0.5488  0.5928
 0.7152  0.8443
[torch.FloatTensor of size 2x2]

In [17]:
#Same seed in Torch again
torch.manual_seed(0)
torch.rand(2,2)


 0.5488  0.5928
 0.7152  0.8443
[torch.FloatTensor of size 2x2]

In [18]:
#No Seed
torch.rand(2,2)


 0.6028  0.8579
 0.5449  0.8473
[torch.FloatTensor of size 2x2]

### Seed for GPU is different for now...
If you want to set a seed when using GPU for computing, you have to use do the following. Seeds for the CPU are independent from the GPU

In [19]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

### 1.4 Numpy and Torch Bridge

In [20]:
# Numpy Array
np_array = np.ones((2,2))

In [21]:
print(np_array)

[[ 1.  1.]
 [ 1.  1.]]


In [22]:
type(np_array)

numpy.ndarray

In [23]:
#Convert to Torch Tensor
torch_tensor = torch.from_numpy(np_array)

In [24]:
print(torch_tensor)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]



In [25]:
type(torch_tensor)

torch.DoubleTensor

When working with Tensors in Torch, data types matter. Below is an intentional error illustrating this point. 

In [28]:
#data types matter; intentional error here:
np_array_new = np.ones((2,2), dtype=np.int8)
print(type(np_array_new))
torch.from_numpy(np_array_new)

<class 'numpy.ndarray'>


RuntimeError: can't convert a given np.ndarray to a tensor - it has an invalid type. The only supported types are: double, float, int64, int32, and uint8.

#### Conversion to torch from numpy supports these types:
1. double
2. float
3. int64, int32, uint8

In [31]:
#int64
np_array_new = np.ones((2,2), dtype=np.int64)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.LongTensor of size 2x2]

In [32]:
#int32
np_array_new = np.ones((2,2), dtype=np.int32)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.IntTensor of size 2x2]

In [33]:
#uint8
np_array_new = np.ones((2,2), dtype=np.uint8)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.ByteTensor of size 2x2]

In [34]:
#float64
np_array_new = np.ones((2,2), dtype=np.float64)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]

In [35]:
#float32
np_array_new = np.ones((2,2), dtype=np.float32)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [36]:
#double
np_array_new = np.ones((2,2), dtype=np.double)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]

### This info is useful when trying to convert Numpy arrays to Torch Tensors and we encounter errors. Now we know which numpy data type is required for which type of Torch Tensor

### Torch to Numpy

In [37]:
torch_tensor = torch.ones(2,2)

In [38]:
type(torch_tensor)

torch.FloatTensor

In [41]:
#Converting to Numpy array is as easy as:
torch_to_numpy = torch_tensor.numpy()

In [42]:
type(torch_to_numpy)

numpy.ndarray

### 1.5 Moving Tensors from CPU to GPU and vice versa

In [43]:
#CPU
tensor_cpu = torch.ones(2,2)

In [44]:
#CPU to GPU
if torch.cuda.is_available():
    tensor_cpu.cuda() #.cuda() method creates the tensor in the gpu 

In [45]:
#GPU to CPU
tensor_cpu.cpu()


 1  1
 1  1
[torch.FloatTensor of size 2x2]

### 1.6 Tensor Operations (let's get mathy with it)

### Resizing Tensors

In [46]:
a = torch.ones((2,2))
print(a)


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [47]:
print(a.size())

torch.Size([2, 2])


In [48]:
a.view(4)


 1
 1
 1
 1
[torch.FloatTensor of size 4]

In [50]:
print(a.view(4).size())

torch.Size([4])


### Element-wise Addition

In [52]:
a = torch.ones((2,2))
print(a)


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [53]:
b = torch.ones((2,2))
print(b)


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [54]:
c = a + b 
print(c)


 2  2
 2  2
[torch.FloatTensor of size 2x2]



In [55]:
#Alternate syntax
c = torch.add(a, b)
print(c)


 2  2
 2  2
[torch.FloatTensor of size 2x2]



In [56]:
#In-place addition i.e. adding to an existing tensor in-place (not assigning to a new variable)
print("old c tensor")
print(c)

c.add_(a)  #The underscore represents in-place operations 

print('-'*60)
print('new c tensor')
print(c)

old c tensor

 2  2
 2  2
[torch.FloatTensor of size 2x2]

------------------------------------------------------------
new c tensor

 3  3
 3  3
[torch.FloatTensor of size 2x2]



### Element-wise Subtraction

In [57]:
print(a)
print(b)


 1  1
 1  1
[torch.FloatTensor of size 2x2]


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [58]:
a-b


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [59]:
#Not in-place
print(a.sub(b))
print(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [60]:
# In-place subtraction. That is, modifying the original tensor. 
print(a.sub_(b))
print(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 0  0
 0  0
[torch.FloatTensor of size 2x2]



### Element-wise Multiplication

In [62]:
a = torch.ones((2,2))
print(a)
b = torch.zeros((2,2))
print(b)


 1  1
 1  1
[torch.FloatTensor of size 2x2]


 0  0
 0  0
[torch.FloatTensor of size 2x2]



In [63]:
a*b


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [65]:
#Not in-place, but showing alternate syntax
print(torch.mul(a,b))
print(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [66]:
#In-place example
print(a.mul_(b))
print(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 0  0
 0  0
[torch.FloatTensor of size 2x2]



### Element-wise Division

In [67]:
a = torch.ones((2,2))
b = torch.zeros((2,2))

In [68]:
b / a


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [69]:
torch.div(b,a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [70]:
b.div_(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [71]:
a


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [72]:
b


 0  0
 0  0
[torch.FloatTensor of size 2x2]

### Tensor Mean

* 1+2+3+4+5+6+7+8+9+10 = 55
* mean = 55/10 = 5.5

In [74]:
# create torch tensor from list
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.size()

torch.Size([10])

In [75]:
a.mean(dim=0)


 5.5000
[torch.FloatTensor of size 1]

In [76]:
a.mean(dim=1) #Intentional error, since this is a 1-D tensor

RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

In [77]:
a = torch.Tensor([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])

In [78]:
a.size()

torch.Size([2, 10])

In [79]:
a.mean(dim=1)


 5.5000
 5.5000
[torch.FloatTensor of size 2]

### Tensor Standard Deviation

In [82]:
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.std(dim=0)


 3.0277
[torch.FloatTensor of size 1]